apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: container-backend
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: backend
spec:
  #type: Load
  type: NodePort
  ports:
  - port: 80
  #nodePort: 30001
  selector:
    app: backend
